### PR TITLE
update links to support lifecycle (#47)

### LINKED ISSUE #47: add event types to message
@wmo-im/tt-wismd 

We should consider adding a "event type" level, for users to be able to subscribe to update/delete workflows, i.e.:

event-type: `created|updated|deleted`

cc @cmheazel following discussions in OGC.

### PR DESCRIPTION
**Pull request by tomkralidis**
Fixes #47.  Related codelists update in https://github.com/wmo-im/wcmp2-codelists/pull/4

### CODE REVIEW

**Review by antje-s — APPROVED** [review]
Maybe it makes sense to add a note in the documentation that the pubtime should be updated in "update" or "deletion" notifications.

**Review by josusky — APPROVED** [review]
Part of me is sad to see ``canonical`` alongside with ``http://def.wmo.int/def/rel/wnm/-/update`` but I understand that as there is no IANA standard relation for what we need we (more or less) have to use a long identifier to ensure uniqueness.

**Comment by tomkralidis** [comment]
@antje-s how about, as a recommendation:

For notifications of updates or deletions, a WNM `properties.pubtime` property SHOULD be updated in support of client handling of change detection.

**Comment by antje-s** [comment]
https://github.com/wmo-im/wis2-notification-message/pull/56#issuecomment-1697183448 
SHALL instead of SHOULD would be better

**Comment by tomkralidis** [comment]
PR already merged, however to your point, if we update from a SHOULD to a SHALL, we need to have an abstract test that compares a message with an update/delete lifecycle, which would be difficult to reproduce given the abstract test would be run against a single payload.

**Comment by antje-s** [comment]
If SHALL causes problems for testing, we could leave SHOULD. An extension or hint could be useful that old pubtime can lead to the fact that the updates/deletions are not taken over correctly

**Comment by tomkralidis** [comment]
@antje-s +1.  Small PR in https://github.com/wmo-im/wis2-notification-message/pull/58 for review/comment.

**Pull request merged**
